make run var="ad 100 lfu"
make run var="ad 70 lfu"
make run var="ad 50 lfu"
make run var="ad 30 lfu"
make run var="ad 20 lfu"
make run var="ad 10 lfu"
make run var="ad 5 lfu"

make run var="user 100 lfu"
make run var="user 70 lfu"
make run var="user 50 lfu"
make run var="user 40 lfu"
make run var="user 30 lfu"
make run var="user 20 lfu"
make run var="user 10 lfu"

make run var="ad 100 lru"
make run var="ad 70 lru"
make run var="ad 50 lru"
make run var="ad 30 lru"
make run var="ad 20 lru"
make run var="ad 10 lru"
make run var="ad 5 lru"

make run var="user 100 lru"
make run var="user 70 lru"
make run var="user 50 lru"
make run var="user 40 lru"
make run var="user 30 lru"
make run var="user 20 lru"
make run var="user 10 lru"